apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-dns

resources:
- base/istio.yaml

patchesJson6902:
- path: overlays/production/azure-dns.yaml
  target:
    group: apps
    kind: Deployment
    name: external-dns
    version: v1
