apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  namespace: argo-cd
  name: istio-ingressgateway
spec:
  selector:
    istio: ingress
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: ingress-cert # This should match the Certificate secretName
    hosts:
    - playground.diehlabs.com # This should match a DNS name in the Certificate
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-cert
  namespace: argo-cd
spec:
  secretName: ingress-cert
  commonName: playground.diehlabs.com
  dnsNames:
  - playground.diehlabs.com
  duration: 2160h0m0s # 90d
  renewBefore: 360h0m0s # 15d
  subject:
    organizations:
      - Diehlabs
  privateKey:
    rotationPolicy: Always
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - any
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: argo-cd
  name: argo-cd-https
spec:
  hosts:
  - playground.diehlabs.com
  gateways:
  - istio-ingressgateway
  http:
  - match:
    - uri:
        prefix: /argocd
    route:
    - destination:
        port:
          number: 80
        host: argocd-server