apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: argocd
  name: argo-cd-https
spec:
  hosts:
  - playground.diehlabs.com
  gateways:
  - istio-ingressgateway
  http:
  - match:
    - uri:
        prefix: /argocd
    route:
    - destination:
        port:
          number: 80
        host: argocd-server