apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd
  project: default
  source:
    path: k8s/aks-config/argo-cd
    repoURL: https://github.com/CultClassik/terraform-aks-playground.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true