apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    path: k8s/argocd/
    repoURL: https://github.com/CultClassik/terraform-aks-playground.git
    targetRevision: HEAD
    helm:
      values: |
        argo-cd:
          metadata:
            namespace: argo-cd
          dex:
            enabled: false
          server:
            extraArgs:
              - --insecure
              - --rootpath
              - /argocd
            config:
              repositories: |
                - type: helm
                  name: argo-cd
                  url: https://argoproj.github.io/argo-helm