apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: azure-workload-identity
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: azure-workload-identity-system
  project: default
  source:
    chart: workload-identity-webhook
    repoURL: https://azure.github.io/azure-workload-identity/charts
    targetRevision: '0.12.0'
    helm:
      values: |
        azureTenantID: fc6ff48d-9858-46be-be10-c3a663f4bcbf
  syncPolicy:
    automated:
      prune: true
      selfHeal: true