apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kiali-operator
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kiali-operator
  project: default
  source:
    chart: kiali-operator
    repository: https://kiali.org/helm-charts
    targetRevision: '1.30.0'
    helm:
      values:
        cr:
          create: true
          namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true