apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

resources:
# - base/cert-manager.yaml
- base/cluster-issuer.yaml
- https://github.com/cert-manager/cert-manager/releases/download/v1.9.1/cert-manager.yaml

patchesJson6902:
- path: overlays/production/azure-dns.yaml
  target:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt
    version: v1
