apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

resources:
# - base/cert-manager.yaml
- https://github.com/cert-manager/cert-manager/releases/download/v1.9.1/cert-manager.yaml
- base/cluster-issuer.yaml

patchesJson6902:
- path: overlays/production/azure-dns.yaml
  target:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt
    version: v1

# helm install \
#   cert-manager jetstack/cert-manager \
#   --namespace cert-manager \
#   --create-namespace \
#   --version ${CERT_MANAGER_VERSION} --set global.leaderElection.namespace=cert-manager