apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base/argo-cd.yaml
# - base/argo-rollouts.yaml
- base/external-dns.yaml
- base/cert-manager.yaml
- base/istio.yaml
# - base/azure-workload-identity.yaml


# - base/ingress-nginx.yaml
# - base/jenkins.yaml
# - base/prometheus-operator.yaml
# - base/istio-operator.yaml
# - base/istio-controlplane.yaml
# - base/istio-addons.yaml
# - base/argocd-image-updater.yaml
# - base/governor.yaml
# - base/argo-workflows.yaml
# - base/argo-events.yaml
# - base/dex.yaml