apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base/argo-rollouts.yaml
- base/azure-workload-identity.yaml
- base/istio.yaml
# dns will create records for istio gateways and vs
- base/external-dns.yaml
# certs will be created for fqdns of gateways
- base/cert-manager.yaml
# these will create their own istio gateways
- base/argo-cd.yaml # argo will need a re-start so that envoy proxies get injected
- base/kiali.yaml

# - demos/nginx.yaml

# - base/ingress-nginx.yaml
# - base/jenkins.yaml
# - base/prometheus-operator.yaml
# - base/istio-operator.yaml
# - base/istio-controlplane.yaml
# - base/istio-addons.yaml
# - base/argocd-image-updater.yaml
# - base/governor.yaml
# - base/argo-workflows.yaml
# - base/argo-events.yaml
# - base/dex.yaml
