apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: httpbin-prod

resources:
- ../../base

patchesJson6902:
  - target:
      version: v1
      group: apps
      kind: Deployment
      name: httpbin
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
  - target:
      version: v1alpha3
      group: networking.istio.io
      kind: VirtualService
      name: httpbin
    patch: |-
      - op: replace
        path: /spec/http/0/match/0/uri/prefix
        value: httpbin/prod