apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: istio-system
---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: istio-ingress
  labels:
    istio-injection: enabled
