apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2022-08-14T19:13:33Z"
  labels:
    kubernetes.io/metadata.name: kiali-operator
    name: kiali-operator
  name: kiali-operator
  uid: 1fffe7c0-510c-4100-8be3-9f4a78cbe3fe
spec:
  finalizers:
  - kubernetes
status:
  phase: Active