apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: httpbin-dev
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: httpbin-dev
  project: default
  source:
    path: k8s/apps-manifests/httpbin/overlays/dev
    repoURL: https://github.com/CultClassik/terraform-aks-playground.git
    targetRevision: HEAD
  syncPolicy:
    # syncOptions:
    #   - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
