apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  source:
    path: k8s/apps-manifests/istio
    repoURL: https://github.com/CultClassik/terraform-aks-playground
    targetRevision: HEAD
 # this ensures argocd doesn't see the app as constantly out of sync
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jqPathExpressions:
       - .webhooks[]?.namespaceSelector.matchExpressions
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jqPathExpressions:
       - .webhooks[]?.namespaceSelector.matchExpressions.control-plane