# The cluster issuer requires a k8s secret for the spn client secret
# create ahead of time for now, later use vault
# apiVersion: v1
# kind: Secret
# metadata:
#   name: azuredns-config
#   namespace: cert-manager
# type: Opaque
# data:
#   client-secret: <base64 encoded spn client secret>
# ---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer # can be namespace specific using Issuer or "global" using ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: "https://acme-v02.api.letsencrypt.org/directory"
    email: aks-cert-mgr@diehlabs.com
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - dns01:
          azureDNS:
            clientSecretSecretRef:
              key: client-secret
              name: azuredns-config
            environment: AzurePublicCloud
            tenantID: fc6ff48d-9858-46be-be10-c3a663f4bcbf
